// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 딥링크 데이터 (Flutter ↔ Native 공유)
///
/// Generated class from Pigeon that represents data sent in messages.
struct VLDeepLinkData {
  var path: String
  var params: [String?: String?]? = nil
  var shortCode: String? = nil
  var linkId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VLDeepLinkData? {
    let path = pigeonVar_list[0] as! String
    let params: [String?: String?]? = nilOrValue(pigeonVar_list[1])
    let shortCode: String? = nilOrValue(pigeonVar_list[2])
    let linkId: Int64? = nilOrValue(pigeonVar_list[3])

    return VLDeepLinkData(
      path: path,
      params: params,
      shortCode: shortCode,
      linkId: linkId
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      params,
      shortCode,
      linkId,
    ]
  }
}

/// 링크 생성 요청 인자
///
/// Generated class from Pigeon that represents data sent in messages.
struct VLCreateLinkArgs {
  var path: String
  var linkType: String
  var data: [String?: String?]? = nil
  var campaign: String? = nil
  var iosUrl: String? = nil
  var androidUrl: String? = nil
  var webUrl: String? = nil
  var ogTitle: String? = nil
  var ogDescription: String? = nil
  var ogImageUrl: String? = nil
  var channel: String? = nil
  var feature: String? = nil
  var tags: [String?]? = nil
  var expiresAt: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VLCreateLinkArgs? {
    let path = pigeonVar_list[0] as! String
    let linkType = pigeonVar_list[1] as! String
    let data: [String?: String?]? = nilOrValue(pigeonVar_list[2])
    let campaign: String? = nilOrValue(pigeonVar_list[3])
    let iosUrl: String? = nilOrValue(pigeonVar_list[4])
    let androidUrl: String? = nilOrValue(pigeonVar_list[5])
    let webUrl: String? = nilOrValue(pigeonVar_list[6])
    let ogTitle: String? = nilOrValue(pigeonVar_list[7])
    let ogDescription: String? = nilOrValue(pigeonVar_list[8])
    let ogImageUrl: String? = nilOrValue(pigeonVar_list[9])
    let channel: String? = nilOrValue(pigeonVar_list[10])
    let feature: String? = nilOrValue(pigeonVar_list[11])
    let tags: [String?]? = nilOrValue(pigeonVar_list[12])
    let expiresAt: String? = nilOrValue(pigeonVar_list[13])

    return VLCreateLinkArgs(
      path: path,
      linkType: linkType,
      data: data,
      campaign: campaign,
      iosUrl: iosUrl,
      androidUrl: androidUrl,
      webUrl: webUrl,
      ogTitle: ogTitle,
      ogDescription: ogDescription,
      ogImageUrl: ogImageUrl,
      channel: channel,
      feature: feature,
      tags: tags,
      expiresAt: expiresAt
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      linkType,
      data,
      campaign,
      iosUrl,
      androidUrl,
      webUrl,
      ogTitle,
      ogDescription,
      ogImageUrl,
      channel,
      feature,
      tags,
      expiresAt,
    ]
  }
}

/// 결제 시도 요청 인자
///
/// Generated class from Pigeon that represents data sent in messages.
struct VLPaymentArgs {
  var orderId: String
  var amount: Double
  var currency: String
  var linkId: Int64? = nil
  var paymentMethod: String? = nil
  var metadata: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VLPaymentArgs? {
    let orderId = pigeonVar_list[0] as! String
    let amount = pigeonVar_list[1] as! Double
    let currency = pigeonVar_list[2] as! String
    let linkId: Int64? = nilOrValue(pigeonVar_list[3])
    let paymentMethod: String? = nilOrValue(pigeonVar_list[4])
    let metadata: [String?: String?]? = nilOrValue(pigeonVar_list[5])

    return VLPaymentArgs(
      orderId: orderId,
      amount: amount,
      currency: currency,
      linkId: linkId,
      paymentMethod: paymentMethod,
      metadata: metadata
    )
  }
  func toList() -> [Any?] {
    return [
      orderId,
      amount,
      currency,
      linkId,
      paymentMethod,
      metadata,
    ]
  }
}

/// 결제 시도 응답
///
/// Generated class from Pigeon that represents data sent in messages.
struct VLPaymentResult {
  var success: Bool
  var paymentEventId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VLPaymentResult? {
    let success = pigeonVar_list[0] as! Bool
    let paymentEventId = pigeonVar_list[1] as! String

    return VLPaymentResult(
      success: success,
      paymentEventId: paymentEventId
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      paymentEventId,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return VLDeepLinkData.fromList(self.readValue() as! [Any?])
    case 130:
      return VLCreateLinkArgs.fromList(self.readValue() as! [Any?])
    case 131:
      return VLPaymentArgs.fromList(self.readValue() as! [Any?])
    case 132:
      return VLPaymentResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VLDeepLinkData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? VLCreateLinkArgs {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? VLPaymentArgs {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? VLPaymentResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Flutter에서 네이티브 SDK를 호출하는 인터페이스
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ViaLinkHostApi {
  /// SDK 초기화
  func configure(apiKey: String) throws
  /// URL 기반 딥링크 수동 처리
  func handleDeepLink(url: String) throws
  /// 커스텀 이벤트 추적
  func track(eventName: String, data: [String?: String?]?) throws
  /// (Pull API) 마지막 수신된 딥링크 데이터 (동기)
  func getDeepLinkData() throws -> VLDeepLinkData?
  /// (Pull API) 디퍼드 매칭 결과 캐시 (동기)
  func getDeferredLinkData() throws -> VLDeepLinkData?
  /// (Pull API) 딥링크 도착까지 대기 (3초 타임아웃)
  func awaitDeepLinkData(completion: @escaping (Result<VLDeepLinkData?, Error>) -> Void)
  /// (Pull API) 디퍼드 매칭 결과까지 대기
  func awaitDeferredLinkData(completion: @escaping (Result<VLDeepLinkData?, Error>) -> Void)
  /// 링크 생성
  func createLink(args: VLCreateLinkArgs, completion: @escaping (Result<String, Error>) -> Void)
  /// 결제 시도 기록
  func trackPayment(args: VLPaymentArgs, completion: @escaping (Result<VLPaymentResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ViaLinkHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ViaLinkHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ViaLinkHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// SDK 초기화
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let apiKeyArg = args[0] as! String
        do {
          try api.configure(apiKey: apiKeyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    /// URL 기반 딥링크 수동 처리
    let handleDeepLinkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.handleDeepLink\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handleDeepLinkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        do {
          try api.handleDeepLink(url: urlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      handleDeepLinkChannel.setMessageHandler(nil)
    }
    /// 커스텀 이벤트 추적
    let trackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.track\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventNameArg = args[0] as! String
        let dataArg: [String?: String?]? = nilOrValue(args[1])
        do {
          try api.track(eventName: eventNameArg, data: dataArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      trackChannel.setMessageHandler(nil)
    }
    /// (Pull API) 마지막 수신된 딥링크 데이터 (동기)
    let getDeepLinkDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.getDeepLinkData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeepLinkDataChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeepLinkData()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeepLinkDataChannel.setMessageHandler(nil)
    }
    /// (Pull API) 디퍼드 매칭 결과 캐시 (동기)
    let getDeferredLinkDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.getDeferredLinkData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeferredLinkDataChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeferredLinkData()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeferredLinkDataChannel.setMessageHandler(nil)
    }
    /// (Pull API) 딥링크 도착까지 대기 (3초 타임아웃)
    let awaitDeepLinkDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.awaitDeepLinkData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      awaitDeepLinkDataChannel.setMessageHandler { _, reply in
        api.awaitDeepLinkData { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      awaitDeepLinkDataChannel.setMessageHandler(nil)
    }
    /// (Pull API) 디퍼드 매칭 결과까지 대기
    let awaitDeferredLinkDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.awaitDeferredLinkData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      awaitDeferredLinkDataChannel.setMessageHandler { _, reply in
        api.awaitDeferredLinkData { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      awaitDeferredLinkDataChannel.setMessageHandler(nil)
    }
    /// 링크 생성
    let createLinkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.createLink\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createLinkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let argsArg = args[0] as! VLCreateLinkArgs
        api.createLink(args: argsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createLinkChannel.setMessageHandler(nil)
    }
    /// 결제 시도 기록
    let trackPaymentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.trackPayment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackPaymentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let argsArg = args[0] as! VLPaymentArgs
        api.trackPayment(args: argsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackPaymentChannel.setMessageHandler(nil)
    }
  }
}
/// 네이티브에서 Flutter로 이벤트를 전달하는 인터페이스
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ViaLinkFlutterApiProtocol {
  /// App Link / Universal Link 딥링크 수신 콜백
  func onDeepLink(data dataArg: VLDeepLinkData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// 디퍼드 딥링크 매칭 결과 콜백
  func onDeferredDeepLink(data dataArg: VLDeepLinkData?, error errorArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ViaLinkFlutterApi: ViaLinkFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// App Link / Universal Link 딥링크 수신 콜백
  func onDeepLink(data dataArg: VLDeepLinkData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkFlutterApi.onDeepLink\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// 디퍼드 딥링크 매칭 결과 콜백
  func onDeferredDeepLink(data dataArg: VLDeepLinkData?, error errorArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkFlutterApi.onDeferredDeepLink\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg, errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
