// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.vialink.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 딥링크 데이터 (Flutter ↔ Native 공유)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VLDeepLinkData (
  val path: String,
  val params: Map<String?, String?>? = null,
  val shortCode: String? = null,
  val linkId: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VLDeepLinkData {
      val path = pigeonVar_list[0] as String
      val params = pigeonVar_list[1] as Map<String?, String?>?
      val shortCode = pigeonVar_list[2] as String?
      val linkId = pigeonVar_list[3] as Long?
      return VLDeepLinkData(path, params, shortCode, linkId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      params,
      shortCode,
      linkId,
    )
  }
}

/**
 * 링크 생성 요청 인자
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VLCreateLinkArgs (
  val path: String,
  val linkType: String,
  val data: Map<String?, String?>? = null,
  val campaign: String? = null,
  val iosUrl: String? = null,
  val androidUrl: String? = null,
  val webUrl: String? = null,
  val ogTitle: String? = null,
  val ogDescription: String? = null,
  val ogImageUrl: String? = null,
  val channel: String? = null,
  val feature: String? = null,
  val tags: List<String?>? = null,
  val expiresAt: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VLCreateLinkArgs {
      val path = pigeonVar_list[0] as String
      val linkType = pigeonVar_list[1] as String
      val data = pigeonVar_list[2] as Map<String?, String?>?
      val campaign = pigeonVar_list[3] as String?
      val iosUrl = pigeonVar_list[4] as String?
      val androidUrl = pigeonVar_list[5] as String?
      val webUrl = pigeonVar_list[6] as String?
      val ogTitle = pigeonVar_list[7] as String?
      val ogDescription = pigeonVar_list[8] as String?
      val ogImageUrl = pigeonVar_list[9] as String?
      val channel = pigeonVar_list[10] as String?
      val feature = pigeonVar_list[11] as String?
      val tags = pigeonVar_list[12] as List<String?>?
      val expiresAt = pigeonVar_list[13] as String?
      return VLCreateLinkArgs(path, linkType, data, campaign, iosUrl, androidUrl, webUrl, ogTitle, ogDescription, ogImageUrl, channel, feature, tags, expiresAt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      linkType,
      data,
      campaign,
      iosUrl,
      androidUrl,
      webUrl,
      ogTitle,
      ogDescription,
      ogImageUrl,
      channel,
      feature,
      tags,
      expiresAt,
    )
  }
}

/**
 * 결제 시도 요청 인자
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VLPaymentArgs (
  val orderId: String,
  val amount: Double,
  val currency: String,
  val linkId: Long? = null,
  val paymentMethod: String? = null,
  val metadata: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VLPaymentArgs {
      val orderId = pigeonVar_list[0] as String
      val amount = pigeonVar_list[1] as Double
      val currency = pigeonVar_list[2] as String
      val linkId = pigeonVar_list[3] as Long?
      val paymentMethod = pigeonVar_list[4] as String?
      val metadata = pigeonVar_list[5] as Map<String?, String?>?
      return VLPaymentArgs(orderId, amount, currency, linkId, paymentMethod, metadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      orderId,
      amount,
      currency,
      linkId,
      paymentMethod,
      metadata,
    )
  }
}

/**
 * 결제 시도 응답
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VLPaymentResult (
  val success: Boolean,
  val paymentEventId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VLPaymentResult {
      val success = pigeonVar_list[0] as Boolean
      val paymentEventId = pigeonVar_list[1] as String
      return VLPaymentResult(success, paymentEventId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      paymentEventId,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VLDeepLinkData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VLCreateLinkArgs.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VLPaymentArgs.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VLPaymentResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VLDeepLinkData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is VLCreateLinkArgs -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is VLPaymentArgs -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is VLPaymentResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Flutter에서 네이티브 SDK를 호출하는 인터페이스
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ViaLinkHostApi {
  /** SDK 초기화 */
  fun configure(apiKey: String)
  /** URL 기반 딥링크 수동 처리 */
  fun handleDeepLink(url: String)
  /** 커스텀 이벤트 추적 */
  fun track(eventName: String, data: Map<String?, String?>?)
  /** (Pull API) 마지막 수신된 딥링크 데이터 (동기) */
  fun getDeepLinkData(): VLDeepLinkData?
  /** (Pull API) 디퍼드 매칭 결과 캐시 (동기) */
  fun getDeferredLinkData(): VLDeepLinkData?
  /** (Pull API) 딥링크 도착까지 대기 (3초 타임아웃) */
  fun awaitDeepLinkData(callback: (Result<VLDeepLinkData?>) -> Unit)
  /** (Pull API) 디퍼드 매칭 결과까지 대기 */
  fun awaitDeferredLinkData(callback: (Result<VLDeepLinkData?>) -> Unit)
  /** 링크 생성 */
  fun createLink(args: VLCreateLinkArgs, callback: (Result<String>) -> Unit)
  /** 결제 시도 기록 */
  fun trackPayment(args: VLPaymentArgs, callback: (Result<VLPaymentResult>) -> Unit)

  companion object {
    /** The codec used by ViaLinkHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ViaLinkHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ViaLinkHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val apiKeyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.configure(apiKeyArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.handleDeepLink$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.handleDeepLink(urlArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.track$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventNameArg = args[0] as String
            val dataArg = args[1] as Map<String?, String?>?
            val wrapped: List<Any?> = try {
              api.track(eventNameArg, dataArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.getDeepLinkData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDeepLinkData())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.getDeferredLinkData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDeferredLinkData())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.awaitDeepLinkData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.awaitDeepLinkData{ result: Result<VLDeepLinkData?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.awaitDeferredLinkData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.awaitDeferredLinkData{ result: Result<VLDeepLinkData?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.createLink$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val argsArg = args[0] as VLCreateLinkArgs
            api.createLink(argsArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkHostApi.trackPayment$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val argsArg = args[0] as VLPaymentArgs
            api.trackPayment(argsArg) { result: Result<VLPaymentResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * 네이티브에서 Flutter로 이벤트를 전달하는 인터페이스
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class ViaLinkFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ViaLinkFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /** App Link / Universal Link 딥링크 수신 콜백 */
  fun onDeepLink(dataArg: VLDeepLinkData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkFlutterApi.onDeepLink$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(dataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** 디퍼드 딥링크 매칭 결과 콜백 */
  fun onDeferredDeepLink(dataArg: VLDeepLinkData?, errorArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vialink_flutter_plugin.ViaLinkFlutterApi.onDeferredDeepLink$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(dataArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
